### ISSUE TITLE
How could it will integrate with ionic 3 

### ISSUE THREAD

**Issue by nishathul** [ArunYogi/paytm-cordova-plugin#4]
Hi 
Please provide how to integrate this plugin in ionic 3. More documentation expects

**Comment by ArunYogi** [comment]
Currently I havent created any ionic-native plugin interface for the paytm-cordova-plugin. Integration of this plugin should not be changing from ionic 2 to ionic 3, just that declaration of paytm variable can be done in respective ts file where you are calling the payment transaction, rather than declaration.ts
